# Generated by Django 5.2.4 on 2025-08-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_editora_rename_biogra_autor_biografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='ano_publicado',
            field=models.DateField(),
        ),
    ]
